### PR TITLE
Add python 3 support and other fixes

### PR DESCRIPTION
**Pull request by davidh-ssec**
This PR merges a few repositories together based on various google search and github search results. It takes the python 3 support from https://github.com/ejeschke/aggdraw but modifies it to make sure that `draw.mode` returns a `str` object in python 2 and python 3 instead of a `bytes` object.

Includes other fixes from @mraspaud and various compiler warning fixes.

### CODE REVIEW

**Comment by davidh-ssec** [comment]
@jakul Martin and I have been talking and wondering if we could/should request PyPI access from `effbot` (https://pypi.python.org/pypi/aggdraw/1.1-20051010). @mraspaud and I would also be OK taking the `pytroll/aggdraw` repository as the main maintained repository of this project. I'm not sure what is best for the project, but since your repository is the most popular of all the `aggdraw`s what do you think?

**Comment by jakul** [comment]
@davidh-ssec I'm happy to transfer this repo over to that organisation, or to delete this repo completely, of for you to update the README to point to that one as the maintained repo.

As far as I know few people use this repo (as evidenced by the quantity of PR's and issues), but for those who do still use aggdraw it's definitely better for them to know that the code you maintain is more up-to-date.

You have my blessings to proceed as you think is best.

**Comment by a-hurst** [comment]
@davidh-ssec just tested it out, it detected my system's freetype installation without a hitch! Thanks so much.

**Comment by mraspaud** [comment]
@jakul Yes, we can take the repo inside the pytroll organisation, no problem. IIUC github should keep a link between jakul/aggdraw and pytroll/aggdraw after that, so no dead link issues :)

**Comment by jakul** [comment]
@mraspaud I just tried to transfer, but becuase you already have a repo with the same name it's not possible. I think you need to merge any changes from your repo into this one and then delete it before I can transfer this one to you.

**Comment by mraspaud** [comment]
@davidh-ssec can you remove the repo ?

**Comment by davidh-ssec** [comment]
@jakul Thanks. The pytroll repos has been deleted.

**Comment by jakul** [comment]
Eugh - "You don’t have the permission to create repositories on pytroll". @davidh-ssec Can you see the options in the repo settings to transfer this repo over to PyTroll?

**Comment by davidh-ssec** [comment]
@jakul Nope. I don't have a settings tab for this repository. You'll have to make me a full collaborator I think.

**Comment by jakul** [comment]
There's an invite waiting for you. I think you can accept on https://github.com/jakul/aggdraw/invitations

**Comment by jakul** [comment]
Or maybe you have an outstanding notification?

**Comment by davidh-ssec** [comment]
Accepted the invitation. Still no settings. How about we add you to the pytroll org just for now so you can move the repository? Wow this got complicated.

**Comment by jakul** [comment]
image


Woohooo!

**Comment by davidh-ssec** [comment]
Nice. Looks like we are good to go. I'll remove you from the organization now...unless you want to start working on meteorological satellite data processing. :)

**Pull request merged**
